name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: gha-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: ./upstream
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-with-warpbuild-docker-builders:
    name: Build with WarpBuild Docker Builders
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: WarpBuilds/build-push-action@v6
        with:
          context: ./upstream
          profile-name: benchmark-builder-dispatch
